"""Opus escalation — Phase 05.

When a finding has confidence < 0.70 or is on the critical-path rule list,
escalate to Claude Opus for a second-pass review.

The Opus call receives:
- The original finding (rule_id, draft_comment_text, severity, evidence summary)
- The skill text for the relevant discipline
- A structured prompt asking Opus to: confirm, reject, or upgrade the finding

Output:
- EscalationResult: original_finding_id, escalated, new_confidence, revised_comment, verdict
  where verdict is "confirmed" | "rejected" | "upgraded"

Escalation is OPTIONAL — only runs when anthropic_api_key is provided.
Costs ~$15/1M output tokens for Opus; log every call.
"""
from __future__ import annotations

import hashlib
import json
import logging
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import anthropic

from inzohra_shared.critical_path import requires_licensed_review

logger = logging.getLogger(__name__)

_OPUS_MODEL = "claude-opus-4-5"
_SONNET_COST_IN = 3e-6
_SONNET_COST_OUT = 15e-6
_OPUS_COST_IN = 15e-6
_OPUS_COST_OUT = 75e-6

# Path: services/review/app/opus_escalation.py → up 4 parents → repo root → skills/
_SKILLS_ROOT = Path(__file__).resolve().parent.parent.parent.parent / "skills"


@dataclass
class EscalationResult:
    original_finding_id: str
    rule_id: str
    discipline: str
    escalated: bool             # True if Opus was actually called
    verdict: str                # "confirmed" | "rejected" | "upgraded" | "skipped"
    original_confidence: float
    new_confidence: float
    revised_comment: str | None  # None if verdict == "confirmed"
    prompt_hash: str | None
    model: str | None
    tokens_in: int = 0
    tokens_out: int = 0
    cost_usd: float = 0.0
    latency_ms: int = 0


def _load_skill(discipline: str) -> str:
    """Load the discipline SKILL.md, return text or empty string."""
    # discipline may be "fire_life_safety" but dir is "fire-life-safety"
    dir_name = discipline.replace("_", "-")
    skill_path = _SKILLS_ROOT / dir_name / "SKILL.md"
    if skill_path.exists():
        return skill_path.read_text(encoding="utf-8")
    return f"[Skill file not found for {discipline}]"


_ESCALATION_PROMPT = """\
You are a senior building official reviewing an AI-generated plan check finding.
The finding below was generated by a deterministic rule system and may need refinement.

Your task: given the finding and the relevant code references, determine if the finding is:
1. "confirmed" — the finding is accurate and the draft comment is appropriate
2. "upgraded" — the finding is accurate but the comment should be strengthened or the confidence increased
3. "rejected" — the finding is a false positive and should be suppressed

Return valid JSON only. No markdown, no explanation. Example:
{"verdict": "confirmed", "new_confidence": 0.88, "revised_comment": null, "rationale": "..."}
or
{"verdict": "upgraded", "new_confidence": 0.95, "revised_comment": "Revised stronger comment...", "rationale": "..."}
or
{"verdict": "rejected", "new_confidence": 0.20, "revised_comment": null, "rationale": "..."}
"""


def should_escalate(rule_id: str, confidence: float) -> bool:
    """Return True if this finding should be escalated to Opus."""
    return confidence < 0.70 or requires_licensed_review(rule_id)


def escalate_finding(
    *,
    finding_id: str,
    rule_id: str,
    discipline: str,
    draft_comment_text: str,
    severity: str,
    confidence: float,
    evidence_summary: str,
    citation_ids: list[str],
    anthropic_api_key: str,
    call_log_rows: list[dict[str, Any]],
) -> EscalationResult:
    """Run Opus second-pass on a single finding.

    Returns an EscalationResult. If verdict == "rejected", the caller should
    suppress the finding (not delete from DB, but mark as suppressed).
    If verdict == "upgraded", the caller should update confidence and comment.
    """
    if not should_escalate(rule_id, confidence):
        return EscalationResult(
            original_finding_id=finding_id,
            rule_id=rule_id,
            discipline=discipline,
            escalated=False,
            verdict="skipped",
            original_confidence=confidence,
            new_confidence=confidence,
            revised_comment=None,
            prompt_hash=None,
            model=None,
        )

    skill_text = _load_skill(discipline)

    finding_summary = {
        "finding_id": finding_id,
        "rule_id": rule_id,
        "severity": severity,
        "confidence": confidence,
        "draft_comment": draft_comment_text,
        "evidence_summary": evidence_summary,
        "citations": citation_ids,
    }

    user_msg = (
        f"## Discipline Skill\n{skill_text[:3000]}\n\n"
        f"## Finding to Review\n{json.dumps(finding_summary, indent=2)}\n\n"
        f"Verdict?"
    )

    prompt_hash = hashlib.sha256(
        (_ESCALATION_PROMPT + user_msg).encode()
    ).hexdigest()[:16]

    client = anthropic.Anthropic(api_key=anthropic_api_key)
    t0 = time.perf_counter()
    call_id = str(uuid.uuid4())

    try:
        response = client.messages.create(
            model=_OPUS_MODEL,
            max_tokens=512,
            temperature=0,
            system=_ESCALATION_PROMPT,
            messages=[{"role": "user", "content": user_msg}],
        )
    except anthropic.APIError as exc:
        logger.error("Opus escalation API error for finding %s: %s", finding_id, exc)
        return EscalationResult(
            original_finding_id=finding_id,
            rule_id=rule_id,
            discipline=discipline,
            escalated=False,
            verdict="confirmed",  # default to confirmed on API error
            original_confidence=confidence,
            new_confidence=confidence,
            revised_comment=None,
            prompt_hash=prompt_hash,
            model=_OPUS_MODEL,
        )

    latency_ms = int((time.perf_counter() - t0) * 1000)
    tokens_in = response.usage.input_tokens
    tokens_out = response.usage.output_tokens
    cost_usd = tokens_in * _OPUS_COST_IN + tokens_out * _OPUS_COST_OUT

    call_log_rows.append({
        "call_id": call_id,
        "prompt_hash": prompt_hash,
        "model": _OPUS_MODEL,
        "tokens_in": tokens_in,
        "tokens_out": tokens_out,
        "latency_ms": latency_ms,
        "cost_usd": cost_usd,
        "caller_service": "review_escalation",
    })

    raw = ""
    for block in response.content:
        if getattr(block, "type", None) == "text":
            raw += block.text

    # Strip markdown fences
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("\n", 1)[-1] if "\n" in cleaned else cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3].rstrip()

    try:
        parsed: dict[str, Any] = json.loads(cleaned)
    except json.JSONDecodeError:
        logger.warning(
            "Opus escalation: JSON parse error for finding %s: %r",
            finding_id,
            raw[:100],
        )
        return EscalationResult(
            original_finding_id=finding_id,
            rule_id=rule_id,
            discipline=discipline,
            escalated=True,
            verdict="confirmed",
            original_confidence=confidence,
            new_confidence=confidence,
            revised_comment=None,
            prompt_hash=prompt_hash,
            model=_OPUS_MODEL,
            tokens_in=tokens_in,
            tokens_out=tokens_out,
            cost_usd=cost_usd,
            latency_ms=latency_ms,
        )

    verdict = str(parsed.get("verdict", "confirmed"))
    new_conf = float(parsed.get("new_confidence", confidence))
    revised = parsed.get("revised_comment")

    logger.info(
        "Opus escalation: finding=%s rule=%s verdict=%s new_conf=%.2f latency=%dms cost=%.5f",
        finding_id,
        rule_id,
        verdict,
        new_conf,
        latency_ms,
        cost_usd,
    )

    return EscalationResult(
        original_finding_id=finding_id,
        rule_id=rule_id,
        discipline=discipline,
        escalated=True,
        verdict=verdict,
        original_confidence=confidence,
        new_confidence=new_conf,
        revised_comment=str(revised) if revised else None,
        prompt_hash=prompt_hash,
        model=_OPUS_MODEL,
        tokens_in=tokens_in,
        tokens_out=tokens_out,
        cost_usd=cost_usd,
        latency_ms=latency_ms,
    )


def batch_escalate(
    findings: list[dict[str, Any]],
    *,
    anthropic_api_key: str,
    call_log_rows: list[dict[str, Any]],
    max_escalations: int = 20,
) -> list[EscalationResult]:
    """Escalate up to max_escalations findings. Findings that should_escalate take priority.

    findings: list of dicts with keys: finding_id, rule_id, discipline,
              draft_comment_text, severity, confidence, evidence_summary, citation_ids
    """
    # Sort: critical path first, then by ascending confidence
    to_escalate = [
        f for f in findings
        if should_escalate(f["rule_id"], f["confidence"])
    ]
    to_escalate.sort(key=lambda f: (
        not requires_licensed_review(f["rule_id"]),
        f["confidence"],
    ))
    to_escalate = to_escalate[:max_escalations]

    results: list[EscalationResult] = []
    for f in to_escalate:
        result = escalate_finding(
            finding_id=f["finding_id"],
            rule_id=f["rule_id"],
            discipline=f["discipline"],
            draft_comment_text=f["draft_comment_text"],
            severity=f["severity"],
            confidence=f["confidence"],
            evidence_summary=f.get("evidence_summary", ""),
            citation_ids=f.get("citation_ids", []),
            anthropic_api_key=anthropic_api_key,
            call_log_rows=call_log_rows,
        )
        results.append(result)

    return results
